# Generated by Django 5.1.7 on 2025-03-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_role_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_role_approved',
            field=models.BooleanField(default=False),
        ),
    ]
